// ШТАБ · кокпит — безопасный мост между окном и системой.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('штаб', {
  isApp: true,
  listProjects: () => ipcRenderer.invoke('projects:list'),
  groupList: () => ipcRenderer.invoke('groups:list'),
  tailsList: () => ipcRenderer.invoke('tails:list'),
  syncStatus: () => ipcRenderer.invoke('sync:status'),
  syncFetch: () => ipcRenderer.invoke('sync:fetch'),
  syncPreview: () => ipcRenderer.invoke('sync:preview'),
  syncPush: (ids) => ipcRenderer.invoke('sync:push', ids),
  syncDiverge: (id) => ipcRenderer.invoke('sync:diverge', id),
  syncPull: () => ipcRenderer.invoke('sync:pull'),
  termInfo: () => ipcRenderer.invoke('term:info'),
  termSessions: () => ipcRenderer.invoke('term:sessions'),
  envCheck: () => ipcRenderer.invoke('env:check'),
  demoOn: () => ipcRenderer.invoke('demo:on'),
  demoOff: () => ipcRenderer.invoke('demo:off'),
  demoIsOn: () => ipcRenderer.invoke('demo:is-on'),
  getStatus: (id, dir) => ipcRenderer.invoke('status:get', id, dir),
  refreshStatus: (id, dir) => ipcRenderer.invoke('status:refresh', id, dir),
  overview: (p) => ipcRenderer.invoke('project:overview', p),
  readFile: (p) => ipcRenderer.invoke('file:read', p),
  openFolder: (p) => ipcRenderer.invoke('folder:open', p),
  openExternal: (u) => ipcRenderer.invoke('shell:open-external', u),
  copyPath: (p) => ipcRenderer.invoke('path:copy', p),
  settingsGet: () => ipcRenderer.invoke('settings:get'),
  settingsAddRoot: () => ipcRenderer.invoke('settings:addRoot'),
  settingsRemoveRoot: (d) => ipcRenderer.invoke('settings:removeRoot', d),
  openFolderTerminal: (dir) => ipcRenderer.invoke('folder:terminal', dir),
  onAppCmd: (fn) => ipcRenderer.on('app:cmd', (_e, data) => fn(data)),
  agentList: () => ipcRenderer.invoke('agent:list'),
  agentRun: (id, dir, prompt) => ipcRenderer.invoke('agent:run', id, dir, prompt),
  agentDiff: (id) => ipcRenderer.invoke('agent:diff', id),
  agentLog: (id) => ipcRenderer.invoke('agent:log', id),
  agentExplain: (id) => ipcRenderer.invoke('agent:explain', id),
  agentAccept: (id) => ipcRenderer.invoke('agent:accept', id),
  agentReject: (id) => ipcRenderer.invoke('agent:reject', id),
  onAgentUpdate: (fn) => ipcRenderer.on('agent:update', () => fn()),
  usageStats: () => ipcRenderer.invoke('usage:stats'),
  boardManifest: (dir) => ipcRenderer.invoke('board:manifest', dir),
  schoolInfo: (dir) => ipcRenderer.invoke('school:info', dir),
  schoolFind: () => ipcRenderer.invoke('school:find'),
  refreshAllStatuses: () => ipcRenderer.invoke('status:refresh-all'),
  onBulkStatus: (fn) => ipcRenderer.on('status:bulk-done', () => fn()),
  boardBlock: (dir, block) => ipcRenderer.invoke('board:block', dir, block),
  searchAll: (q) => ipcRenderer.invoke('search:all', q),
  askAll: (q) => ipcRenderer.invoke('ask:all', q),
  loadNotes: () => ipcRenderer.invoke('notes:load'),
  saveNotes: (t) => ipcRenderer.invoke('notes:save', t),
  notesSync: () => ipcRenderer.invoke('notes:sync'),
  webStart: () => ipcRenderer.invoke('web:start'),
  webStop: () => ipcRenderer.invoke('web:stop'),
  webStatus: () => ipcRenderer.invoke('web:status'),
  seenGet: () => ipcRenderer.invoke('seen:get'),
  seenMark: (id) => ipcRenderer.invoke('seen:mark', id),
  seenInit: (ids) => ipcRenderer.invoke('seen:init', ids),
  waitingSince: (items) => ipcRenderer.invoke('waiting:since', items),
  snoozeGet: () => ipcRenderer.invoke('snooze:get'),
  snoozeAdd: (id) => ipcRenderer.invoke('snooze:add', id),
  healthGet: () => ipcRenderer.invoke('health:get'),
  healthLog: (entries) => ipcRenderer.invoke('health:log', entries),
  boardTemplates: () => ipcRenderer.invoke('board:templates'),
  boardCreate: (dir, key) => ipcRenderer.invoke('board:create', dir, key),
  lessonsAsk: (q) => ipcRenderer.invoke('lessons:ask', q),
  linksMap: () => ipcRenderer.invoke('links:map'),
  didSince: (days) => ipcRenderer.invoke('did:since', days),
  talksSearch: (q) => ipcRenderer.invoke('talks:search', q),
  wallList: () => ipcRenderer.invoke('wall:list'),
  pickWall: (id) => ipcRenderer.invoke('wall:pick', id),
  resetWall: (id) => ipcRenderer.invoke('wall:reset', id),
});
